---
#
# create on dev
#

- hosts: localhost
  connection: local

  vars:
    dev_users:
      - username: alice
        became_oracle: [dev]
        became_root: [dev]
        server_groups: [dev]

      - username: bob
        became_oracle: [sit]
        became_root: [dev]
        server_groups: [dev, sit]

      - username: carmen
        became_oracle: [dev, dit, uat]
        became_root: [dev]
        server_groups: [dev, sit, uat]

      - username: derek
        became_oracle: [dev, sit, uat, prod]
        became_root: [dev]
        server_groups: [dev, sit, uat, prod]

  tasks:
    - name: create user directory
      become: yes
      file:
        path: "/opt/pmaker/dev/{{ item.username }}/.ssh"
        state: directory
        owner: "{{ item }}"
        mode: u+r,g-w+x,o+x
        recurse: yes
        
    - name: generate SSH key "{{ item.username }}"
      openssh_keypair:
        path: "/opt/pmaker/dev/{{ item.username }}/.ssh"
        type: rsa
        size: 4096
        state: present
        force: no
      with_items: '{{ dev_users }}'

    - include: user_create.yml
      with_items: '{{ dev_users }}'

    - name: Add user to sudo
      become: yes
      lineinfile:
        path: "/etc/sudoers.d/{{ item.username }}"
        line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: yes
        validate: "visudo -cf %s"
      when: "'dev' in item.became_root"
      with_items: '{{ dev_users }}'