---
#
# create on dev
#

- hosts: localhost
  connection: local

  vars:
    server_group: dev

  tasks:
    #
    # execute on controller
    #
    - include_vars: dev_users.yaml

    - name: create user directory
      become: yes
      file:
        path: "/opt/pmaker/dev/{{ item.username }}/.ssh"
        state: directory
        owner: "pmaker"
        mode: u+r,g-w+x,o+x
        recurse: yes
      with_items: '{{ users }}'

    - name: generate SSH key "{{ item.username }}"
      become: yes
      openssh_keypair:
        path: "/opt/pmaker/dev/{{ item.username }}/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no
      with_items: '{{ users }}'

    - name: Generate Passwords
      become: no
      local_action: command pwgen --symbols --numerals --capitalize --ambiguous 12
      with_items: '{{ users }}'
      register: user_passwords

    - name: Save Passwords Locally
      become: no
      local_action: copy content={{ item.stdout }} dest="/opt/pmaker/dev/{{ item.item }}/.ssh/secret.txt"
      with_items: '{{ user_passwords.results }}'

- hosts: dev

  vars:
    server_group: dev

    #
    # execute on remote host
    #
  tasks:
    - include_vars: dev_users.yaml

    - include: user_create.yml
      with_items: '{{ users }}'

    - name: Update User Passwords
      user:
        name: '{{ item.item }}'
        password: '{{ item.stdout }}'
      with_items: '{{ user_passwords.results }}'
      
    - name: Add user to sudo
      become: yes
      lineinfile:
        path: "/etc/sudoers.d/{{ item.username }}"
        line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: yes
        validate: "visudo -cf %s"
      when: "'dev' in item.became_root"
      with_items: '{{ users }}'