---
#
# create on dev
#


#
# execute on controller
#
- hosts: localhost
  connection: local

  vars:
      server_group: dev

  tasks:
    - include_vars: config.yaml
    - include_vars: "{{ pmaker_home }}/state/{{ user_group }}/{{ server_group }}/users.yaml"

    - include: "{{ pmaker_home }}/lib/user_gen_key.yaml"
      with_items: '{{ users }}'
      
    - include: "{{ pmaker_home }}/lib/user_gen_password.yaml"
      with_items: '{{ users }}'

#
# execute on remote host
#
- hosts: dev

  vars:
      server_group: dev

  tasks:
    - include_vars: config.yaml
    - include_vars: "{{ pmaker_home }}/state/{{ user_group }}/{{ server_group }}/users.yaml"

    - include: "{{ pmaker_home }}/lib/user_create.yaml"
      with_items: '{{ users }}'

    - include: "{{ pmaker_home }}/lib/user_set_key.yaml"
      with_items: '{{ users }}'

    - include: "{{ pmaker_home }}/lib/user_set_password.yaml"
      with_items: '{{ users }}'

    - name: Add user to root sudoers
      become: yes
      lineinfile:
        path: "/etc/sudoers.d/{{ item.username }}"
        line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: yes
        validate: "visudo -cf %s"
      #[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: '{{ server_group }}' in item.became_root
      #when: "'{{ user_group }}' in item.became_root"
      when: "'dev' in item.became_root"
      with_items: '{{ users }}'

    - name: Add user to oracle sudoers
      become: yes
      blockinfile:
        path: "/etc/sudoers.d/{{ item.username }}"
        block: |
          {{ item.username }} ALL=(root) NOPASSWD: /bin/su oracle
          {{ item.username }} ALL=(root) NOPASSWD: /bin/su - oracle
        state: present
        mode: 0440
        create: yes
        validate: "visudo -cf %s"
      when: "'dev' in item.became_oracle"
      with_items: '{{ users }}'

    - name: Add user to appl sudoers
      become: yes
      blockinfile:
        path: "/etc/sudoers.d/{{ item.username }}"
        block: |
          {{ item.username }} ALL=(root) NOPASSWD: /bin/su appl*
          {{ item.username }} ALL=(root) NOPASSWD: /bin/su - appl*
        state: present
        mode: 0440
        create: yes
        validate: "visudo -cf %s"
      when: "'dev' in item.became_appl"
      with_items: '{{ users }}'
