---
#
# create on dev
#


#
# execute on controller
#
- hosts: localhost
  connection: local

  vars:
      server_group: dev

  tasks:
    - include_vars: config.yaml
    - include_vars: "{{ pmaker_home }}/state/{{ server_group }}/users.yaml"

    - name: create user directory
      become: yes
      file:
        path: "{{ pmaker_home }}/state/{{ user_group }}/{{ server_group }}/{{ item.username }}/.ssh"
        state: directory
        owner: "pmaker"
        mode: u+r,g-w+x,o+x
        recurse: yes
      with_items: '{{ users }}'

    - name: generate SSH key "{{ item.username }}"
      become: yes
      openssh_keypair:
        path: "{{ pmaker_home }}/state/{{ user_group }}/{{ server_group }}/{{ item.username }}/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no
      with_items: '{{ users }}'

    - include: "{{ pmaker_home }}/lib/user_gen_password.yaml"
      with_items: '{{ users }}'

#
# execute on remote host
#
- hosts: dev

  vars:
      server_group: dev

  tasks:
    - include_vars: config.yaml
    - include_vars: "{{ pmaker_home }}/state/{{ user_group }}/{{ server_group }}/users.yaml"

    - include: "{{ pmaker_home }}/lib/user_create.yaml"
      with_items: '{{ users }}'

    - include: "{{ pmaker_home }}/lib/user_set_password.yaml"
      with_items: '{{ users }}'

    - name: Add user to root sudoers
      become: yes
      lineinfile:
        path: "/etc/sudoers.d/{{ item.username }}"
        line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: yes
        validate: "visudo -cf %s"
      #[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: '{{ server_group }}' in item.became_root
      #when: "'{{ user_group }}' in item.became_root"
      when: "'dev' in item.became_root"
      with_items: '{{ users }}'