---
#
# select users belonging to given environment
#

- hosts: localhost
  connection: local

  tasks:
    - include_vars: config.yaml
    - include_vars: "{{ pmaker_home }}/data/{{ user_group }}.users.yaml"

    #
    # write dev users to user_group/users.yaml
    #
    - name: set fact
      set_fact:
        users_subset: "{{ users_subset|default([]) + [ item ]  }}"

      when: server_group in item.server_groups
      with_items: "{{users}}"

    - name: Create state directory
      file:
        path: "{{ pmaker_home }}/state/{{ user_group }}/dev"
        state: directory
      when: users_subset is defined

    - name: Write users_subset to a file
      copy:
        content: "{{ users_subset | to_nice_yaml }}"
        dest: "{{ pmaker_home }}/state/{{ user_group }}/dev/users.yaml"
      when: users_subset is defined

    - name: Insert proper header
      shell: sed -i '1 i\---\nusers:' "{{ pmaker_home }}/state/{{ user_group }}/dev/users.yaml"
      when: users_subset is defined
