---
#
# select users belonging to given environment
# known: dev, sit, uat, prod
#

- hosts: localhost
  connection: local

  tasks:
    - include_vars: "{{ pmaker_home }}/data/{{ user_group }}.yaml"

    #
    # write dev users to dev_users.yaml
    #
    - name: set fact
      set_fact:
        dev_users: "{{ dev_users|default([]) + [ item ]  }}"

      when: "'dev' in item.server_groups"
      with_items: "{{users}}"

    - name: Create state directory
      file:
        path: "{{ pmaker_home }}/state/{{ user_group }}/dev"
        state: directory

    - name: Write dev_users to a file
      copy:
        content: "{{ dev_users | to_nice_yaml }}"
        dest: "{{ pmaker_home }}/state/{{ user_group }}/dev/users.yaml"

    - name: Insert proper header
      shell: sed -i '1 i\---\nusers:' "{{ pmaker_home }}/state/{{ user_group }}/dev/users.yaml"

    #
    # write sit users to sit_users.yaml
    #
    - name: set fact
      set_fact:
        sit_users: "{{ sit_users|default([]) + [ item ]  }}"

      when: "'sit' in item.server_groups"
      with_items: "{{users}}"

    - name: Create state directory
      file:
        path: "{{ pmaker_home }}/state/{{ user_group }}/sit"
        state: directory

    - name: Write sit_users to a file
      copy:
        content: "{{ sit_users | to_nice_yaml }}"
        dest: "{{ pmaker_home }}/state/{{ user_group }}/sit/users.yaml"

    - name: Insert proper header
      shell: sed -i '1 i\---\nusers:' "{{ pmaker_home }}/state/{{ user_group }}/sit/users.yaml"


    #
    # write uat users to uat_users.yaml
    #
    - name: set fact
      set_fact:
        uat_users: "{{ uat_users|default([]) + [ item ]  }}"

      when: "'uat' in item.server_groups"
      with_items: "{{users}}"

    - name: Create state directory
      file:
        path: "{{ pmaker_home }}/state/{{ user_group }}/uat"
        state: directory

    - name: Write uat_users to a file
      copy:
        content: "{{ uat_users | to_nice_yaml }}"
        dest: "{{ pmaker_home }}/state/{{ user_group }}/uat/users.yaml"

    - name: Insert proper header
      shell: sed -i '1 i\---\nusers:' "{{ pmaker_home }}/state/{{ user_group }}/uat/users.yaml"


    #
    # write prod users to prod_users.yaml
    #
    - name: set fact
      set_fact:
        prod_users: "{{ prod_users|default([]) + [ item ]  }}"

      when: "'prod' in item.server_groups"
      with_items: "{{users}}"

    - name: Create state directory
      file:
        path: "{{ pmaker_home }}/state/{{ user_group }}/prod"
        state: directory

    - name: Write prod_users to a file
      copy:
        content: "{{ prod_users | to_nice_yaml }}"
        dest: "{{ pmaker_home }}/state/{{ user_group }}/prod/users.yaml"

    - name: Insert proper header
      shell: sed -i '1 i\---\nusers:' "{{ pmaker_home }}/state/{{ user_group }}/prod/users.yaml"
