---
#
# select users belonging to given environment
# known: dev, sit, uat, prod
#

- hosts: localhost
  connection: local

  vars:
    pmaker_home: /opt/pmaker

  tasks:
    - include_vars: "{{ pmaker_home }}/data/users.yaml"

    #
    # write dev users to dev_users.yaml
    #
    - name: set fact
      set_fact:
        dev_users: "{{ dev_users|default([]) + [ item ]  }}"

      when: "'dev' in item.server_groups"
      with_items: "{{users}}"

    - name: Write dev_users to a file
      copy:
        content: "{{ dev_users | to_nice_yaml }}"
        dest: "{{ pmaker_home }}/state/dev/users.yaml"

    #
    # write sit users to sit_users.yaml
    #
    - name: set fact
      set_fact:
        sit_users: "{{ sit_users|default([]) + [ item ]  }}"

      when: "'sit' in item.server_groups"
      with_items: "{{users}}"

    - name: Write sit_users to a file
      copy:
        content: "{{ sit_users | to_nice_yaml }}"
        dest: "{{ pmaker_home }}/state/sit/users.yaml"

    #
    # write uat users to uat_users.yaml
    #
    - name: set fact
      set_fact:
        uat_users: "{{ uat_users|default([]) + [ item ]  }}"

      when: "'uat' in item.server_groups"
      with_items: "{{users}}"

    - name: Write uat_users to a file
      copy:
        content: "{{ uat_users | to_nice_yaml }}"
        dest: "{{ pmaker_home }}/state/uat/users.yaml"

    #
    # write prod users to prod_users.yaml
    #
    - name: set fact
      set_fact:
        prod_users: "{{ prod_users|default([]) + [ item ]  }}"

      when: "'prod' in item.server_groups"
      with_items: "{{users}}"

    - name: Write prod_users to a file
      copy:
        content: "{{ prod_users | to_nice_yaml }}"
        dest: "{{ pmaker_home }}/state/prod/users.yaml"
