---
- hosts: all
  become: true
  tasks:
  - name: Enable password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp='^#?PasswordAuthentication' line='PasswordAuthentication yes'
    notify:
    - restart sshd

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
