---
#
# revoke pmaker keys from all hosts
#   
- hosts: all

  tasks:
  - include_vars: ../config.yaml

  - include: pmaker_revoke_key.yaml
    with_items: 
      - "{{ root_pmaker }}"
    when: (pmaker_type is defined) and (pmaker_type == "global")

  # - include: ../lib/user_revoke_key.yaml
  #   with_items: 
  #     - "{{ env_pmaker }}"
  #   when: (pmaker_type is defined) and (pmaker_type == "env")
