---
#
# remove pmaker users
# 
# !!! USE ONLY DURING INTIAL SETUP !!! 
# THIS PROCEDURE REMOVES HOME DIRECTORY
#
# - hosts: all
#   become: yes

#   tasks:
#     - include: ../lib/user_remove.yaml
#       with_items: 
#         - pmaker

#
# create pmaker user, pmaker home directory, copy keys to pmaker home
#
- hosts: controller
  tasks:
  - include: pmaker_create_home.yaml
    with_items: 
      - pmaker  

#
# create pmaker users on all hosts; verify that key is in place
#
- hosts: all
  tasks:
  - include: pmaker_create_workers.yaml
    with_items: 
      - {{ global_pmaker }} 
    when: global_pmaker is defined


  handlers:
    - name: restart sshd
      service: name=sshd state=restarted