---

#
# revoke pmaker keys on all hosts; verify that key is in place
#
- hosts: all
  tasks:
  - include: pmaker_revoke_key.yaml
    with_items: 
      - "{{ env_pmaker }}"

  - include: ../lib/user_revoke_key.yaml
    with_items: 
      - "{{ env_pmaker }}"


