---

#
# revoke pmaker keys on all hosts; verify that key is in place
#
- hosts: localhost

  tasks:
  - include_vars: ../config.yaml

  - include: pmaker_revoke_key.yaml
    with_items: 
      - "{{ root_pmaker }}"
      
- hosts: all

  tasks:
  - include_vars: ../config.yaml

  - include: ../lib/user_revoke_key.yaml
    with_items: 
      - "{{ env_pmaker }}"
