---
#
# remove pmaker users
#
# - hosts: all
#   tasks:
#     - include: users_remove.yml
#       with_items: 
#         - pmaker

#
# create pmaker user, pmaker home directory, copy keys to pmaker home
#
- hosts: controller
  tasks:
  - include: pmaker_create_home.yml
    with_items: 
      - pmaker  

#
# create pmaker users on all hosts; verify that key is in place
#
- hosts: all
  tasks:
  - include: pmaker_create_workers.yml
    with_items: 
      - pmaker  

