---
#
# create pmaker user, pmaker home directory, copy keys to pmaker home
#
- hosts: controller
  tasks:
  - include_vars: ../config.yaml

  # master pmaker is owner of the pmaker controller.
  # you use this account to connect to coltroller
  # you use this account to define and push changes
  - include: pmaker_create_home.yaml
    with_items: 
      - "{{ root_pmaker }}"  
    when: (pmaker_type is defined) and (pmaker_type == "global")

  # env pmaker is a worker deplyed at managed servers' side
  - include: "{{ pmaker_home }}/lib/user_gen_key.yaml"
    with_items: 
      - "{{ env_pmaker }}"
    when: (pmaker_type is defined) and (pmaker_type == "env")

#
# create pmaker users on all hosts; verify that key is in place
#
- hosts: all
  tasks:
  - include_vars: ../config.yaml

  - include: pmaker_create_workers.yaml
    with_items: 
      - "{{ root_pmaker }}"
    when: (pmaker_type is defined) and (pmaker_type == "global")

- hosts: all
  tasks:
  - include: pmaker_create_env_workers.yaml
    with_items: 
      - "{{ env_pmaker }}"
    when: (pmaker_type is defined) and (pmaker_type == "env")

  # TODO move to server preparation
  handlers:
    - name: restart sshd
      command: sudo service sshd restart