---
#
# revoke pmaker keys from all hosts
#   
- hosts: all

  tasks:
  - include_vars: ../config.yaml

  # - include: pmaker_revoke_key.yaml
  #   with_items: 
  #     - "{{ root_pmaker }}"

  - include: ../lib/user_revoke_key.yaml
    with_items: 
      - "{{ env_pmaker }}"
